Repository Project60/org.project60.sepa, pull requests merged in 2024-08, with the labels that each got.

#722 Fix or issue 721
  CRM/Sepa/Logic/Queue/Close.php
Labels: needs funding

#726 Error: Failed opening required 'CRM/Sepa/CustomData.php'
  CRM/Sepa/Upgrader.php
Labels: bug

#728 Avoid strtotime smarty modifier
  CRM/Sepa/Page/DashBoard.php
  templates/CRM/Sepa/Page/DashBoard.tpl
Labels: enhancement

#730 Replace deprecated `${}` syntax for referencing variables in strings
  CRM/Sepa/BAO/SEPATransactionGroup.php
  CRM/Sepa/Logic/Batching.php
  CRM/Sepa/Page/CreateMandate.php
  CRM/Utils/SepaCustomisationHooks.php
Labels: bug, status:needs review

#732 Fix `ts()` calls with variable strings
  CRM/Sepa/Logic/Format.php
  CRM/Sepa/Logic/Queue/Update.php
  l10n/org.project60.sepa.pot
Labels: bug, status:needs review

#610 Use more reliable method to generate unique mandate reference
  CRM/Sepa/BAO/SEPAMandate.php
Labels: enhancement, status:needs work
