Repository Project60/org.project60.sepa, pull requests merged in 2024-03, with the labels that each got.

#699 Fixed bug in the new token evaluation
  CRM/Utils/SepaTokens.php
  sepa.php
Labels: enhancement, bug, status:reviewed and tested

#702 Define permissions in the correct format (with `label` and `description`)
  sepa.php
Labels: enhancement, CiviCRM 5.x, status:needs review

#700 #655 Created "mark group received" runner
  CRM/Sepa/Logic/Group.php
  CRM/Sepa/Logic/Queue/Close.php
  CRM/Sepa/Page/MarkGroupReceived.php
  templates/CRM/Sepa/Page/DashBoard.tpl
  xml/Menu/sepa.xml
Labels: enhancement

#704 Upgrade Civix-generated code to Civix version 23.02.1
  CRM/Sepa/Upgrader.php
  CRM/Sepa/Upgrader/Base.php
  info.xml
  mixin/entity-types-php@1.0.0.mixin.php
  mixin/menu-xml@1.0.0.mixin.php
  mixin/mgd-php@1.0.0.mixin.php
  mixin/polyfill.php
  mixin/smarty-v2@1.0.1.mixin.php
  sepa.civix.php
  sepa.php
Labels: bug, status:reviewed and tested
